# Generated by Django 2.2.13 on 2020-08-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_auto_20200818_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='source_subscribed',
            field=models.CharField(choices=[('Web', 'Website footer'), ('Con', 'Contact us'), ('Inv', 'Invitation')], default='Web', max_length=1),
        ),
    ]
