# Generated by Django 2.2.13 on 2020-08-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0004_auto_20200830_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='preferred_contact_method',
            field=models.CharField(choices=[('ph', 'phone'), ('E', 'email')], default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='source_subscribed',
            field=models.CharField(choices=[('Web', 'Website footer'), ('Con', 'Contact us'), ('Inv', 'Invitation')], default='Web', max_length=3),
        ),
    ]
