version: "3"

services:
    frontend:
        build:
            context: .
            dockerfile: ./node.Dockerfile
        volumes:
            - .:/app/
            - frontend_file:/app/frontend/
        working_dir: /app
        command: sh -c "
            npm run build"

    backend:
        build:
            context: .
            dockerfile: ./django.Dockerfile
        volumes:
            - .:/app/
            - ./InproactSite/settings.py:/app/InproactSite/settings.py:ro
            - frontend_file:/app/frontend/
            - media_file:/app/media_root/
        working_dir: /app
        command: sh -c "
            sleep 2
            && python manage.py migrate --noinput
            && python manage.py collectstatic --noinput --force-color
            && python manage.py runserver 0.0.0.0:8088"
        ports:
            - "8088:8088"
        expose:
            - 8088
        depends_on:
            - frontend

    nginx:
        image: nginx:1.19.0-alpine
        ports:
            - 80:80
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
            - frontend_file:/app/frontend/
            - media_file:/app/media_root/
        depends_on:
            - frontend
            - backend

volumes:
    frontend_file:
    media_file:
