version: "3"

services:
    inpro_frontend:
        build:
            context: .
            dockerfile: ./node.Dockerfile
        volumes:
            - .:/app/
        working_dir: /app
        command: sh -c "
            yarn install &&
            yarn run build"

    inpro_backend:
        build:
            context: .
            dockerfile: ./django.Dockerfile
        volumes:
            - .:/app/
            - ./InproactSite/settings.py:/app/InproactSite/settings.py:ro
        working_dir: /app
        command: sh -c "
            mkdir -p /app/frontend/static_root
            && python manage.py migrate --noinput -v 0
            && python manage.py collectstatic --noinput --force-color -v 0
            && gunicorn --workers 5 --bind 0.0.0.0:8088 InproactSite.wsgi:application"
        ports:
            - "8088:8088"
        depends_on:
            - inpro_frontend

    inpro_nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - 8082:80
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
            - ./frontend/static:/app/frontend/static
            - ./media_root:/app/media_root/
        depends_on:
            - inpro_frontend
            - inpro_backend

