# Generated by Django 2.2.13 on 2020-08-05 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitemain',
            name='active',
        ),
    ]
