# Generated by Django 2.2.13 on 2020-08-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_websitemain_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemain',
            name='active_content',
            field=models.BooleanField(default=False),
        ),
    ]
