# Generated by Django 2.2.13 on 2020-08-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_websitemain_active_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemain',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='website_main/'),
        ),
    ]
