# Generated by Django 2.2.13 on 2020-08-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_websitemain_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_1_2_divider',
            new_name='section_1_heading',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_1_words',
            new_name='section_1_paragraph1',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_text_1_paragraph',
            new_name='section_1_paragraph2',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_text_1_title',
            new_name='section_2_heading',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_text_2_paragraph',
            new_name='section_2_paragraph1',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_text_3_paragraph',
            new_name='section_2_paragraph2',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_text_2_title',
            new_name='section_2_title',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_text_3_title',
            new_name='section_3_heading',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_text_4_paragraph',
            new_name='section_3_paragraph1',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_text_4_title',
            new_name='section_3_title',
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_3_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_3_picture',
            field=models.ImageField(blank=True, upload_to='website_main/'),
        ),
    ]
