# Generated by Django 2.2.13 on 2020-08-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200808_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemain',
            name='section_1_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_2_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_3_activate',
            field=models.BooleanField(default=True),
        ),
    ]
