# Generated by Django 2.2.13 on 2020-08-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200808_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_1_heading',
            new_name='section_1_heading1',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_1_title',
            new_name='section_1_heading2',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_heading',
            new_name='section_2_heading1',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_2_title',
            new_name='section_2_heading2',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_3_heading',
            new_name='section_3_heading1',
        ),
        migrations.RenameField(
            model_name='websitemain',
            old_name='section_3_title',
            new_name='section_3_heading2',
        ),
    ]
