# Generated by Django 2.2.13 on 2020-08-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200808_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemain',
            name='section_1_subheading1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websitemain',
            name='section_1_subheading2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websitemain',
            name='section_2_subheading1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websitemain',
            name='section_2_subheading2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websitemain',
            name='section_3_subheading1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websitemain',
            name='section_3_subheading2',
            field=models.TextField(blank=True),
        ),
    ]
