# Generated by Django 2.2.13 on 2020-08-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200809_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_caption1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_caption2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_caption3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_number1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_number2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_number3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_title1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_title2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_1_stat_title3',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
