# Generated by Django 2.2.13 on 2020-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200809_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemain',
            name='section_1_stat_caption1',
            field=models.TextField(blank=True),
        ),
    ]
