# Generated by Django 2.2.13 on 2020-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200809_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemain',
            name='section_2_stat_number1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_2_stat_number2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_2_stat_number3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_2_stat_number4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_2_stat_title1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_2_stat_title2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_2_stat_title3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='websitemain',
            name='section_2_stat_title4',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
