# Generated by Django 2.2.13 on 2020-08-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='preferred_contact',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='query',
            name='subject',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[('bus', 'Business'), ('ind', 'Individual'), ('cont', 'General Contact')], default='cont', max_length=4),
        ),
    ]
