# Generated by Django 2.2.13 on 2020-08-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20200826_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='premade_message',
            new_name='checked_content',
        ),
    ]
