# Generated by Django 2.2.13 on 2020-08-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20200826_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='note_internal_use',
            field=models.TextField(blank=True, null=True),
        ),
    ]
