# Generated by Django 2.2.13 on 2020-08-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='logo2',
        ),
    ]
