# Generated by Django 2.2.13 on 2020-08-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_remove_aboutus_logo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='logo2',
            field=models.FileField(default=1, upload_to='aboutus/'),
            preserve_default=False,
        ),
    ]
