# Generated by Django 2.2.13 on 2020-07-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_auto_20200711_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='logo',
            field=models.FileField(upload_to='aboutus/'),
        ),
    ]
