# Generated by Django 2.2.13 on 2020-08-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_aboutus_logo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='logo2',
        ),
    ]
