# Generated by Django 2.2.13 on 2020-08-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_remove_aboutus_logo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='name',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='button_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='famous_quote',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='light_background_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section1_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section1_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section2_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section2_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section3_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section3_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section3_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
