# Generated by Django 2.2.13 on 2020-08-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_auto_20200804_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='famous_quote',
            field=models.TextField(blank=True),
        ),
    ]
