# Generated by Django 2.2.13 on 2020-08-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_auto_20200804_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='section4_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section4_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section4_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
