# Generated by Django 2.2.13 on 2020-08-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_auto_20200804_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_background_image', models.FileField(blank=True, upload_to='sidepages/aboutus')),
                ('AboutUs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.AboutUs')),
            ],
        ),
    ]
