# Generated by Django 2.2.13 on 2020-08-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='famous_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section1_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section1_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='story',
            name='section2_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section2_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='story',
            name='section3_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus'),
        ),
        migrations.AddField(
            model_name='story',
            name='section3_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section3_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
