# Generated by Django 2.2.13 on 2020-08-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0009_auto_20200805_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='AboutUs',
        ),
        migrations.AddField(
            model_name='story',
            name='aboutus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutus.AboutUs'),
        ),
    ]
