# Generated by Django 2.2.13 on 2020-08-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_auto_20200805_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='section1_title',
            new_name='section1_heading_1',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='section2_title',
            new_name='section2_heading_1',
        ),
        migrations.RemoveField(
            model_name='story',
            name='famous_quote',
        ),
        migrations.RemoveField(
            model_name='story',
            name='light_background_image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='section1_paragraph',
        ),
        migrations.RemoveField(
            model_name='story',
            name='section2_paragraph',
        ),
        migrations.RemoveField(
            model_name='story',
            name='section3_image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='section3_paragraph',
        ),
        migrations.RemoveField(
            model_name='story',
            name='section3_title',
        ),
        migrations.AddField(
            model_name='story',
            name='button_name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus/story'),
        ),
        migrations.AddField(
            model_name='story',
            name='main_section_heading',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='main_section_paragraph',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section1_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus/story'),
        ),
        migrations.AddField(
            model_name='story',
            name='section1_paragraph_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section1_quote_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section1_subparagraph_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section1_subparagraph_2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section1_subparagraph_3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section2_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus/story'),
        ),
        migrations.AddField(
            model_name='story',
            name='section2_paragraph_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section2_quote_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section2_subparagraph_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section2_subparagraph_2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='section2_subparagraph_3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
