# Generated by Django 2.2.13 on 2020-08-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0011_auto_20200805_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='active_content',
            field=models.BooleanField(default=False),
        ),
    ]
