# Generated by Django 2.2.13 on 2020-08-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0012_aboutus_active_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.FileField(blank=True, upload_to='sidepages/aboutus/team')),
                ('button_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('section1_image', models.FileField(blank=True, upload_to='sidepages/aboutus/team')),
                ('section1_heading_1', models.CharField(blank=True, max_length=1000)),
                ('section1_paragraph_1', models.TextField(blank=True, default=None, null=True)),
                ('section1_subparagraph_1', models.TextField(blank=True, default=None, null=True)),
                ('section1_subparagraph_2', models.TextField(blank=True, default=None, null=True)),
                ('section1_subparagraph_3', models.TextField(blank=True, default=None, null=True)),
                ('section1_quote_1', models.TextField(blank=True, default=None, null=True)),
                ('section2_image', models.FileField(blank=True, upload_to='sidepages/aboutus/team')),
                ('section2_heading_1', models.CharField(blank=True, max_length=1000)),
                ('section2_paragraph_1', models.TextField(blank=True, default=None, null=True)),
                ('section2_subparagraph_1', models.TextField(blank=True, default=None, null=True)),
                ('section2_subparagraph_2', models.TextField(blank=True, default=None, null=True)),
                ('section2_subparagraph_3', models.TextField(blank=True, default=None, null=True)),
                ('section2_quote_1', models.TextField(blank=True, default=None, null=True)),
                ('aboutus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutus.AboutUs')),
            ],
        ),
    ]
