# Generated by Django 2.2.13 on 2020-08-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0014_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus/services'),
        ),
    ]
