# Generated by Django 2.2.13 on 2020-08-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0016_whyus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'AboutUs', 'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Story'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name': 'WhyUs', 'verbose_name_plural': 'WhyUs'},
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_1_2_divider',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_1_picture',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_2_picture',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_2_text_2_paragraph',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_2_text_2_title',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_2_text_3_paragraph',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_2_text_3_title',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_2_text_4_paragraph',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='section_2_text_4_title',
        ),
    ]
