# Generated by Django 2.2.13 on 2020-08-17 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0018_auto_20200817_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whyussubitem',
            options={'verbose_name': 'Why Us SubItem', 'verbose_name_plural': 'Why Us SubItems'},
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='whyus_subitem',
        ),
        migrations.RemoveField(
            model_name='whyussubitem',
            name='whyusId',
        ),
        migrations.AddField(
            model_name='whyussubitem',
            name='aboutus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutus.AboutUs'),
        ),
    ]
