# Generated by Django 2.2.13 on 2020-08-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0019_auto_20200817_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='whyus_subitem_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
