# Generated by Django 2.2.13 on 2020-08-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0020_services_whyus_subitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='whyus_subitem_title',
        ),
        migrations.AddField(
            model_name='whyus',
            name='whyus_subitem_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
