# Generated by Django 2.2.13 on 2020-08-18 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0021_auto_20200817_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyussubitem',
            name='aboutus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whyus_subitems', to='aboutus.AboutUs'),
        ),
    ]
