# Generated by Django 2.2.13 on 2020-08-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0022_auto_20200818_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
