# Generated by Django 2.2.13 on 2020-08-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0023_auto_20200831_0901'),
        ('aboutus', '0023_auto_20200830_2058'),
    ]

    operations = [
    ]
