# Generated by Django 2.2.13 on 2020-08-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frontend',
        ),
    ]
