// Constants
export const GET_ABOUTUS = "GET_ABOUTUS";
export const GET_MAINPAGE = "GET_MAINPAGE";
export const GET_SERVICES = "GET_SERVICES";

export const MOUSE_ENTER = "MOUSE_ENTER";
export const MOUSE_CLICK = "MOUSE_CLICK";
export const AUTO = "AUTO";

export const ADD_SUBSCRIBER = "ADD_SUBSCRIBER";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";


export const GET_WEBSITEPAGES_REQUEST = "GET_WEBSITEPAGES_REQUEST";
export const GET_WEBSITEPAGES_SUCCESS = "GET_WEBSITEPAGES_SUCCESS";
export const GET_WEBSITEPAGES_FAILURE = "GET_WEBSITEPAGES_FAILURE";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const ADD_QUERY = "ADD_QUERY";
export const ADD_QUERY_SUCCESS = "ADD_QUERY_SUCCESS";
export const ADD_QUERY_FAILURE = "ADD_QUERY_FAILURE";