# Generated by Django 2.2.13 on 2020-08-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0002_auto_20200823_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepages',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='websitepages/contact'),
        ),
    ]
