# Generated by Django 2.2.13 on 2020-08-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='embed_map_frame',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_description_primary',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_description_secondary',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_primary',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_secondary',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
