# Generated by Django 2.2.13 on 2020-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0005_auto_20200824_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_map_link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
