# Generated by Django 2.2.13 on 2020-08-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0006_contact_address_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsTickBoxItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('individual_use', models.BooleanField(default=False)),
                ('Business_use', models.BooleanField(default=False)),
                ('contactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitePages.Contact')),
            ],
            options={
                'verbose_name': 'Contact Preset Query',
                'verbose_name_plural': 'Contact Preset Queries',
            },
        ),
    ]
