# Generated by Django 2.2.13 on 2020-08-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0007_contactustickboxitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactustickboxitems',
            name='contactId',
        ),
        migrations.AddField(
            model_name='contactustickboxitems',
            name='websitePages',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='websitePages.WebsitePages'),
            preserve_default=False,
        ),
    ]
