# Generated by Django 2.2.13 on 2020-08-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0008_auto_20200826_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactustickboxitems',
            options={'verbose_name': 'Tickbox', 'verbose_name_plural': 'Tickbox'},
        ),
        migrations.RemoveField(
            model_name='contactustickboxitems',
            name='websitePages',
        ),
        migrations.AddField(
            model_name='contactustickboxitems',
            name='contactId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickboxs', to='websitePages.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactustickboxitems',
            name='websitePagesID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='websitePages.WebsitePages'),
            preserve_default=False,
        ),
    ]
