# Generated by Django 2.2.13 on 2020-08-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0010_remove_contactustickboxitems_websitepagesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactustickboxitems',
            name='contactId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickboxs', to='websitePages.Contact'),
        ),
    ]
