# Generated by Django 2.2.13 on 2020-08-26 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0013_auto_20200826_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactustickboxitems',
            old_name='Business_use',
            new_name='business_use',
        ),
    ]
