# Generated by Django 2.2.13 on 2020-08-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0014_auto_20200826_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitepages',
            options={'verbose_name': 'Website Page', 'verbose_name_plural': 'Website Pages'},
        ),
    ]
