# Generated by Django 2.2.13 on 2020-08-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0016_ourbrand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourbrand',
            options={'verbose_name': 'OurBrand', 'verbose_name_plural': 'OurBrand'},
        ),
    ]
