# Generated by Django 2.2.13 on 2020-08-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0017_auto_20200826_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_1_2_divider',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_1_picture',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_1_title',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_1_words',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_picture',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_text_1_paragraph',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_text_1_title',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_text_2_paragraph',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_text_2_title',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_text_3_paragraph',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_text_3_title',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_text_4_paragraph',
        ),
        migrations.RemoveField(
            model_name='ourbrand',
            name='section_2_text_4_title',
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='sidepages/aboutus/ourbrand'),
        ),
    ]
