# Generated by Django 2.2.13 on 2020-08-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0020_auto_20200827_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourbrand',
            old_name='section_1_content_paragraph',
            new_name='paragraph',
        ),
        migrations.AlterField(
            model_name='contact',
            name='button_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='button_name',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='page_name',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='thread_title_1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='thread_title_2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='thread_title_3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='thread_title_4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='button_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='section_1_2_divider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='section_1_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='section_2_text_1_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='section_2_text_2_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='section_2_text_3_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='section_2_text_4_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='InSight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.FileField(blank=True, upload_to='sidepages/others')),
                ('page_name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('button_name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('quote', models.TextField(blank=True)),
                ('quote_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('paragraph', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('thread_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('websitePages', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websitePages.WebsitePages')),
            ],
            options={
                'verbose_name': 'InSight',
                'verbose_name_plural': 'InSights',
            },
        ),
        migrations.CreateModel(
            name='ICare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.FileField(blank=True, upload_to='sidepages/others')),
                ('page_name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('button_name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('heading', models.TextField(blank=True)),
                ('left_paragraph', models.TextField(blank=True)),
                ('right_paragraph', models.TextField(blank=True)),
                ('right_paragraph_2', models.TextField(blank=True)),
                ('thread_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('websitePages', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websitePages.WebsitePages')),
            ],
            options={
                'verbose_name': 'ICare',
                'verbose_name_plural': 'ICare',
            },
        ),
    ]
