# Generated by Django 2.2.13 on 2020-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0021_auto_20200827_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icare',
            name='button_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='icare',
            name='page_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='button_name',
            field=models.CharField(blank=True, default=None, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='page_name',
            field=models.CharField(blank=True, default=None, max_length=42, null=True),
        ),
    ]
