# Generated by Django 2.2.13 on 2020-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePages', '0022_auto_20200827_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icare',
            name='button_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
